### ISSUE TITLE
biology

### ISSUE THREAD

**Issue by flavens-vmm** [Informatievlaanderen/OSLOthema-airAndWater#1]
**DwC**, the Darwin Core, delivers good formats/standards/framework for biology data.
[https://dwc.tdwg.org/](https://dwc.tdwg.org/)
[https://rs.gbif.org](https://rs.gbif.org/)

**GBIF** can be a resource for checklists/taxonlist.
[https://www.gbif.org/dataset/search?type=CHECKLIST](https://www.gbif.org/dataset/search?type=CHECKLIST)
e.g. [https://www.gbif.org/dataset/search?type=CHECKLIST&publishing_country=BE](https://www.gbif.org/dataset/search?type=CHECKLIST&publishing_country=BE) to search "Belgian" checklists.
Data is provided through webservices.
(It is also possible to publish checklists on GBIF.)

GBIF has a tax backbone, an integration of different sources.
It could be used as a core reference.
[GBIF Backbone Taxonomy](https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c)

GBIF has tools, such as a data validator, a name parser, species matching against the backbone ...

**Comment by KevinHaleydt** [comment]
Thank you for the input Frank. I've added this to the list of possible observed properties in Issue #2

**Comment by KevinHaleydt** [comment]
Resolved during last Thematic workshop
