### ISSUE TITLE
ObservedProperties

### ISSUE THREAD

**Issue by KevinHaleydt** [Informatievlaanderen/OSLOthema-airAndWater#2]
We will need to foresee standardized lists of ObservedProperties. The possible options are to:

1. Leave the lists to be customizable to whomever exchanges data, as long as the properties are identified via a URI (e.g. SKOS:Concept)
2. Suggest which standardized lists to use in the specification
3. Create our own taxonomy or list from what is available

Current code lists that have been raised during the workshops are:

**AIR**
- [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/Phosphoric-acid)
- Other suggestions?

**WATER**
- [WISE](http://dd.eionet.europa.eu/dataelements/75873): Full list can be downloaded as CSV under export section
- [Darwin Core](https://www.gbif.org/dataset/search?type=CHECKLIST): Biology
- [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/Phosphoric-acid)

Our understanding from the discussions during the workshops
Indicate a standardized codelist to use but leave the flexibility to define other properties should they not be present in the codel list that is proposed. 

Please provide your feedback and preferred option in this issue.

Thanks!

Kevin

**Comment by flavens-vmm** [comment]
The link named 'Darwin Core' for biology in water is not a link to the Darwin Core.
The Darwin Core includes a glossary of terms intended to facilitate the sharing of information about biological diversity.
It could be verified that these terms fit in the proposal of  template.

In fact, the link 'Darwin Core' is a link to GBIF, more specifically to the checklists/taxonlists that are in GBIF. 
These are indeed the ObservedProperties for biology, so the link should be renamed to 'GBIF' (or something like that).

In the chat of the workgroup Geert Van Haute has suggested wikidata.org that has an even larger range of indentifiers, among which those from GBIF.

**Comment by stijnvanhoey** [comment]
For Darwin core background, see https://www.tdwg.org/standards/dwc/ or https://github.com/tdwg/dwc

**Comment by KevinHaleydt** [comment]
Initial thoughts to resolve this issue:
1/ We need to be able to link to URI (from a codelist) as well as free text field in case ObservedProperty can't be found in any of the cose lists

2/ Rather than explicitly adding in the model which code list has to be used mandatorily, we specify the prefered codelists to use. 

Based on the codelists currently referenced, the main candidates seem to be 
- PubChem for any type of chemical substance
- wikidata in case we also want to include taxonomy about biological diversity.

At first glance, it looks like wikidata includes both chemical substances as well as biological substances and allows linking these substances to either their CAS/PUBchem/GBIF identificator

example brought up by Geert Van Haute: https://www.wikidata.org/wiki/Q27855
Blue mussel uri + reference to GBIF
![image](https://user-images.githubusercontent.com/41194963/111905061-1fc2b880-8a4a-11eb-9870-0a3344cf8130.png)

example for NH3: https://www.wikidata.org/wiki/Q4087
![image](https://user-images.githubusercontent.com/41194963/111905091-48e34900-8a4a-11eb-84f5-e036e0dbeffa.png)
![image](https://user-images.githubusercontent.com/41194963/111905098-526cb100-8a4a-11eb-9394-6d2a6a06a813.png)

Wikidata links to Pubchem as well as CAS ids. 

Based on this data, initial conclusion seems to be to add in the usage notes that the use of wikidata uris is prefered above Pubchem/GBIF/... However in any we would add the flexibility of a free text.

**Comment by KevinHaleydt** [comment]
Resolved during last Thematic workshop. More information can be found in the slides of Thematic Workshop 3.
