### ISSUE TITLE
Observation.sampledFeature

### ISSUE THREAD

**Issue by KevinHaleydt** [Informatievlaanderen/OSLOthema-airAndWater#3]
Currently we have not modelled out Feature but it looks like this may be needed to cover some of the use cases that were proposed.

**Water** 
For water, we found that WISE proposes the following subdivision:
- Coastal Water
- Groundwater body
- Lake water body
- Marine waters
- River water body
- Territorial waters
- Transitional water body

-> Initial feedback during the workshop pointed out that this list may not be complete and leaves out other water feature types such as sewer water, wastewater...

Is there another standardized list that is complete for water and includes the other subtypes that are needed? 

**Air**
A similar requirement may be needed for Air as well to cover use cases such as stack emissions from industry.
Is there a standard that refers to the specific feature types for Air?

**Comment by KevinHaleydt** [comment]
Further exploration on this needed. As of yet no standardized code list found that goes beyond WISE & includes waste water of sewer (idem for Air)

**Comment by GeertThijs** [comment]
We did some research (see https://github.com/Informatievlaanderen/OSLOthema-airAndWater/blob/master/resources/OGC-WaterML%20WaterQuality%20Profile%20%26%20FeatureOfInterest.pdf) and as a result came up with this list for Water:
![image](https://user-images.githubusercontent.com/22620291/112825895-984df880-908c-11eb-963e-addc7ce8b17e.png)

**Comment by GeertThijs** [comment]
Ok, for Water we have surface waters and groundwater but we are still missing possible sampled Waterfeatures like:

- Waterducts (waterpipes, sewers... ).
- Waterpoints (water sources, sewer outlets...).

Problem there is that we do not sample the ducts and points themselves, but the water that flows through them or comes out of (or goes into?) them. Difficult to treat these as "waterbodies" like in the above list.

REMARK: Water and the void that the water fills are different things, as is reflected in OGC:HY_Hydrofeature where the above list is based upon. In the mentioned standard the so called FluidBody and the Aquifer that is "filled" with it are modelled seterately.

**Comment by laurianvm** [comment]
The environment ontology might provide some suitable candidates:
[liquid water terms](https://www.ebi.ac.uk/ols/ontologies/envo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_00002006&viewMode=All&siblings=false) --> they have terms for 'types' of water, including a few for waste water, e.g. sewage (http://purl.obolibrary.org/obo/ENVO_00002018)

also came across the VEuPathDB vocab, which has a term for 'water piped into a dwelling'  (http://purl.obolibrary.org/obo/EUPATH_0021076) - not sure context of the vocab is suitable though

**Comment by KevinHaleydt** [comment]
Resolved during last Thematic workshop

Addition of Air & Water Feature types will allow to point towards the type of domain feature that is being sampled. In addiditon instances of this class can be created to describe more in depth the domain feature in scope (f.ex. lake, canal...)

More information can be found in the presentation of TW3
