### ISSUE TITLE
Sampling Feature

### ISSUE THREAD

**Issue by KevinHaleydt** [Informatievlaanderen/OSLOthema-airAndWater#4]
We suggest adding an extra class that allows tracking ‘Specimen’. There are two possibilities:

- The WISE model allows pointing towards physical samples by creating two classes: SpatialSamplingFeatures, Specimen.
- SOSA goes more into details by adding SOSA Sampling (the activity of sampling) and SOSA Sampler (the specific instruments used). 

Please let us know which option should be pursued.

**Comment by stijnvanhoey** [comment]
I do think SOSA samplings is a good match to cover grab samples which are analyzed in the lab later on, e.g. in the following simplified (no official protocol ;-)) example: I am interested in water quality of a pond/lake (featureofinterest) and canoe in a straight line/transect across the pond (sosa:Sampling) and I use a 'bucket' (sosa:sampler) to take x times a grab sample (sosa:sample) along the transect. These samples are then analyzed in the lab using sensors (sosa:sensor) and certain protocols (sosa:procedure) to get observations. 

A possible drawback might be that the difference between 'sampler' and 'sensor' (Fiware 'Device') is unclear when using on-line sensors as the sensor itself takes the sample? But in this case one can just ignore 'sampler' part and link the geographical location to the sensor directly?

**Comment by KevinHaleydt** [comment]
Resolved during last Thematic workshop. More information can be found in the slides of Thematic Workshop 3.
