### ISSUE TITLE
Air & Water definitions

### ISSUE THREAD

**Issue by laurianvm** [Informatievlaanderen/OSLOthema-airAndWater#8]
VLIZ' feedback on the air & water definitions: [Definitions main classes & Origins.xlsx](https://github.com/Informatievlaanderen/OSLOthema-airAndWater/files/6350443/Definitions.main.classes.Origins.xlsx)

**Comment by KevinHaleydt** [comment]
Hi Laurian, thx for the input. We will include this input in the workshop of 27th April.

Kind regards

Kevin

**Comment by gezever** [comment]
Dear colleagues
I don't know if you are aware that the pages under purl.eu are only available in English. With a system that is configured in Dutch, you will see "add translation here" everywhere.
Kind regards,
Geert
https://purl.eu/doc/applicationprofile/AirAndWater/Core

**Comment by laurianvm** [comment]
Dear Geert, 
Thank you for your useful remark; it's certainly important to be aware of this issue. 
I believe this concern would be better addressed in a separate issue to ensure proper tracking and resolution.

Kind regards, Laurian
